name: super_test
description: Designed to simplify testing of SuperControllers, RxNotifiers and RxTs.
version: 1.2.0
repository: https://github.com/DrDejaVuNG/super_test
issue_tracker: https://github.com/DrDejaVuNG/super_test/issues
# homepage: https://drdejavu.ng
# documentation: https://super.drdejavu.ng

# publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.0.0

dependencies:
  dart_super: ^1.4.8
  meta: ^1.9.1 
  test: ^1.16.0
  diff_match_patch: ^0.4.1

dev_dependencies:
  lints: 
