name: super_test
description: Designed to simplify testing of SuperControllers, RxNotifiers and RxTs.
version: 1.0.0
repository: https://github.com/DrDejaVuNG/super_test
issue_tracker: https://github.com/DrDejaVuNG/super_test/issues
# homepage: https://drdejavu.ng
# documentation: https://super.drdejavu.ng

# publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.0.3

dependencies:
  flutter:
    sdk: flutter
  flutter_super:  ^1.0.1
  meta: ^1.9.1
  test: ^1.24.3
  diff_match_patch: ^0.4.1

dev_dependencies:
  lints: 
